# Options for analysis running.
run:
    go: '1.21'
    tests: false
    skip-dirs:
        - internal/testutils
linters:
    enable:
      - errcheck
      - gosimple
      - govet
      - ineffassign
      - staticcheck
      - unused
      - bodyclose
      - containedctx
      - decorder
      - errorlint
      - gofmt
      - goimports
      - misspell
      - nilnil
      - whitespace
